### ISSUE TITLE
Buffered IndexedZstdFile fails with numpy deserialization

### ISSUE THREAD

**Issue by dariost** [martinellimarco/indexed_zstd#7]
When using IndexedZstdFile in conjunction with numpy deserialization (`numpy.load`) this leads to a crash due to numpy being advertised a wrong (shorter) file size.

This code triggers the issue:
```python
import numpy as np
import zstandard as zstd
from io import BytesIO
from indexed_zstd import IndexedZstdFile
from tempfile import NamedTemporaryFile

file = NamedTemporaryFile()
A = np.random.random((100, 100))
handler = zstd.open(file.name, "wb")
np.save(handler, A)
handler.close()
handler = IndexedZstdFile(file.name)
B = np.load(handler)
assert np.array_equal(A, B)
```
The resulting execution leads to
```
Traceback (most recent call last):
  File "/tmp/a/bug.py", line 15, in <module>
    B = np.load(handler)
  File "/usr/lib/python3.10/site-packages/numpy/lib/npyio.py", line 440, in load
    return format.read_array(fid, allow_pickle=allow_pickle,
  File "/usr/lib/python3.10/site-packages/numpy/lib/format.py", line 787, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 9381 into shape (100,100)
```
This error does not occur if using IndexedZstdFileRaw instead of IndexedZstdFile.

**Comment by martinellimarco** [comment]
I was able to reproduce the same issue using [indexed_bzip2](https://github.com/mxmlnkn/indexed_bzip2) and [indexed_gzip](https://github.com/pauldmccarthy/indexed_gzip) too so I'm not sure if it's the same bug in all 3 libraries or something in numpy ?

Example for indexed_gzip

```
import numpy as np
import gzip as gz
from tempfile import NamedTemporaryFile
from indexed_gzip import IndexedGzipFile

file = NamedTemporaryFile()
A = np.random.random((100, 100))
handler = gz.open(file.name, "wb")
np.save(handler, A)
handler.close()

f = IndexedGzipFile(file.name, drop_handles=False)
B = np.load(f)
assert np.array_equal(A, B)
```

Example for indexed_bzip2

```
import numpy as np
import bz2
from tempfile import NamedTemporaryFile
from indexed_bzip2 import IndexedBzip2File
from indexed_bzip2 import IndexedBzip2FileRaw

file = NamedTemporaryFile()
A = np.random.random((100, 100))
handler = bz2.open(file.name, "wb")
np.save(handler, A)
handler.close()

f = IndexedBzip2File(file.name)
#f = IndexedBzip2FileRaw(file.name)
B = np.load(f)
assert np.array_equal(A, B)
```

**Comment by martinellimarco** [comment]
The bug is in numpy itself.

numpy.fromfile has [a lot of open issues](https://github.com/numpy/numpy/issues?q=is%3Aissue+is%3Aopen+fromfile) at the moment.

The reason it works with IndexedZstdFileRaw and not with IndexedZstdFile is that the two are evaluated differently by [this if](https://github.com/numpy/numpy/blob/c852e1397bf3c0b24faaa3c66cc50b1f2eba1ebd/numpy/lib/format.py#L754).

For IndexedZstdFile the if evaluate True and the bugged numpy.fromfile is used.

For IndexedZstdFileRaw the if evaluate False and an alternative code is used to process the file.

If you change the if so that it evaluate to False for both IndexedZstdFile and IndexedZstdFileRaw the array is always loaded correctly.
